version: '1'

services:
  backend:
    image: node:20
    build:
      context: ./backend
      dockerfile: ./backend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  frontend:
    image: node:20
    build:
      context: ./frontend
      dockerfile: ./frontend/Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
