version: '3.8'  # Cambiado a una versión más reciente de docker-compose

services:
  backend:
    build:
      context: ./Back_End  # Asegúrate de que el nombre de la carpeta coincide con tu proyecto (Back_End)
      dockerfile: dockerfile  # El Dockerfile está dentro de la carpeta Back_End
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  frontend:
    build:
      context: ./Front_End  # Asegúrate de que el nombre de la carpeta coincide con tu proyecto (Front_End)
      dockerfile: dockerfile  # El Dockerfile está dentro de la carpeta Front_End
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

